version: '3'
services:
  db:
    image: mysql/mysql-server:5.6
    restart: always
    container_name: "mysql_wsl"
    volumes:
      - ../mysql/data:/var/lib/mysql:rw
      - ../mysql/config/my.cnf:/etc/my.cnf:rw
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Tym8zzrnNRpz4
      MYSQL_DATABASE: webstack
      MYSQL_USER: webstack
      MYSQL_PASSWORD: Xym8zzrnNRpz
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    networks:
      - "webstacknet"
  redis:
    image: redis:3
    container_name: "redis_wsl"
    restart: always
    networks:
      - "webstacknet"
  webstack:
    image: arvon2014/webstack-laravel:v1.2.2
    container_name: "wsl"
    volumes:
      - ../website:/opt/navi:rw
    ports:
      - 8000:8000
    depends_on:
      - "db"
      - "redis"
    environment:
      LOGIN_COPTCHA: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webstack
      DB_USERNAME: webstack
      DB_PASSWORD: Xym8zzrnNRpz
    command: ['/entrypoint.sh','server']
    networks:
      - "webstacknet"
networks:
  webstacknet:
    driver: bridge
